---
- name: My first playbook
  hosts: tags_Name_cst_ansible_server
  hosts: tags_Name_c*
  gather_facts: true
  become: true
  vars_files:
    - "vars.yaml"

  roles:
    - send_logs

# tasks:
  #   - debug: msg="my boot image is {{ ansible_cmdline.BOOT_IMAGE}}"
  #   - name: install the latest version of apache
  #     yum:
  #       name: httpd
  #       state: latest
  #   - name: start service httpd, if not started
  #     service:
  #       name: httpd
  #       state: started
  #       enabled: true
  #   - name: change defualt index file
  #     file:
  #       path: /var/www/html/index.html
  #       state: absent